### ISSUE TITLE
Some unicode characters displayed in place of icons

### ISSUE THREAD

**Issue by boardfish** [wstam88/rofi-fontawesome#2]
Where FontAwesome shares a slot with an existing unicode character (I think it's almost exclusively the newer brands e.g. Nintendo Switch), the original unicode character will be displayed. Also visible with icons like Uber, VNV, etc. I'd assume the solution is probably to use FontAwesome with immediate priority over the fallback font, but launching rofi with that font option doesn't change the result.

**Comment by wstam88** [comment]
@boardfish Which version of Fontawesome did you install?

**Comment by boardfish** [comment]
The most recent one available at the time, which I think was 5.0.2.

**Comment by joncol** [comment]
I get the same problem with Font Awesome 5.0.3 using `fa5-icon-list.txt`.

**Comment by wstam88** [comment]
This was due to the fact that FA5 has multiple fonts (brands/solid/regular) and the font family in the icon list was using 'Font Awesome 5 free'  instead of 'Font Awesome 5 (brands|solid|regular)'.

I fixed it in the latest commit.

**Comment by wstam88** [comment]
Note: paid fonts will not work if you don't have them installed.

**Comment by boardfish** [comment]
Thanks for fixing this - it's been a fair while since I've gotten busy with ricing, but this'll be a great incentive to come back.

**Comment by DosAge011** [comment]
I think this is the same issue as discussed here, so I am commenting here as well. The only way I could get all of the chr to display properly was to update the txt files.

replacing **'font Awesome 5 solid'** with **'Font Awesome 5 Free Solid'**
replacing **'font Awesome 5 regular'** with **'Font Awesome 5 Free Regular'**

This sounds like the fix wstam88 was going to make, I just don't see it reflected in the repository. Sorry for beating a dead horse, its a very useful little script and I just wanted to help get it working for others.
